apiVersion: v1
kind: Template
labels:
  template: f8a-worker-scaler
metadata:
  name: f8a-worker-scaler
  annotations:
    description: f8a-worker-scaler
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: f8a-worker-scaler
    name: f8a-worker-scaler
  spec:
    selector:
      service: f8a-worker-scaler
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          service: f8a-worker-scaler
      spec:
        containers:
        - env:
          - name: DEPLOYMENT_PREFIX
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: deployment-prefix
          - name: AWS_SQS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-access-key-id
          - name: AWS_SQS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-secret-access-key
          - name: WORKER_POD_TO_SCALE
            value: "${WORKER_POD_TO_SCALE}"
          - name: SQS_QUEUE_FOR_SCALING
            value: "${SQS_QUEUE_FOR_SCALING}"
          - name: DEFAULT_NUMBER_OF_PODS
            value: "${DEFAULT_NUMBER_OF_PODS}"
          - name: MAX_NUMBER_OF_PODS
            value: "${MAX_NUMBER_OF_PODS}"
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: f8a-worker-scaler
          readinessProbe:
            exec:
              command: ["worker-readiness.sh"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["worker-liveness.sh"]
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 5
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "2048Mi"
        restartPolicy: Always
    triggers:
    - type: ConfigChange

parameters:
- description: Worker region for serving tasks - api or ingestion
  displayName: Worker administration region
  required: true
  name: WORKER_POD_TO_SCALE
  value: "api"

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "fabric8-analytics/worker-scaler"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"  # image-tag
