apiVersion: v1
kind: Template
labels:
  template: f8a-worker-scaler
metadata:
  name: f8a-worker-scaler
  annotations:
    description: f8a-worker-scaler
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: f8a-worker-scaler
    name: f8a-worker-scaler
  spec:
    selector:
      service: f8a-worker-scaler
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          service: f8a-worker-scaler
      spec:
        containers:
        - env:
          - name: DEPLOYMENT_PREFIX
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: deployment-prefix
          - name: AWS_SQS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-access-key-id
          - name: AWS_SQS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-secret-access-key
          - name: DC_NAME
            value: "${DC_NAME}"
          - name: SQS_QUEUE_NAME
            value: "${SQS_QUEUE_NAME}"
          - name: DEFAULT_REPLICAS
            value: "${DEFAULT_REPLICAS}"
          - name: MAX_REPLICAS
            value: "${MAX_REPLICAS}"
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: f8a-worker-scaler
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
        restartPolicy: Always
    triggers:
    - type: ConfigChange

parameters:
- description: Worker region for serving tasks - api or ingestion
  displayName: Worker administration region
  required: true
  name: DC_NAME
  value: "api"

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "fabric8-analytics/worker-scaler"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"  # image-tag
