apiVersion: v1
kind: Template
labels:
  template: f8a-worker-scaler
metadata:
  name: f8a-worker-scaler
  annotations:
    description: f8a-worker-scaler
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: f8a-worker-scaler-${WORKER_POD_TO_SCALE}
    name: f8a-worker-scaler-${WORKER_POD_TO_SCALE}
  spec:
    selector:
      service: f8a-worker-scaler-${WORKER_POD_TO_SCALE}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          service: f8a-worker-scaler-${WORKER_POD_TO_SCALE}
      spec:
        containers:
        - env:
          - name: OPENSHIFT_DEPLOYMENT
            value: "${OPENSHIFT_DEPLOYMENT}"
          - name: DEPLOYMENT_PREFIX
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: deployment-prefix
          - name: AWS_SQS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-access-key-id
          - name: AWS_SQS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-secret-access-key
          - name: AWS_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
               name: aws
               key: s3-access-key-id
          - name: AWS_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: s3-secret-access-key
          - name: BAYESIAN_SYNC_S3
            valueFrom:
              secretKeyRef:
                name: aws
                key: sync-s3
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: worker
                key: github-token
          - name: AWS_S3_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: s3-bucket-for-analyses
          - name: WORKER_POD_TO_SCALE
            value: "${WORKER_POD_TO_SCALE}"
          - name: SQS_QUEUE_FOR_SCALING
            value: "${SQS_QUEUE_FOR_SCALING}"
          - name: DEFAULT_NUMBER_OF_PODS
            value: "${DEFAULT_NUMBER_OF_PODS}"
          - name: MAX_NUMBER_OF_PODS
            value: "${MAX_NUMBER_OF_PODS}"
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: f8a-worker-scaler
          readinessProbe:
            exec:
              command: ["worker-readiness.sh"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["worker-liveness.sh"]
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 5
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "2048Mi"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange

parameters:
- description: Worker region for serving tasks - api or ingestion
  displayName: Worker administration region
  required: true
  name: WORKER_POD_TO_SCALE
  value: "api"

- description: Turn off tasks that are run on OpenShift instance and require internal services
  displayName: Openshift deployment
  required: true
  name: OPENSHIFT_DEPLOYMENT
  value: "1"

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "bayesian/sqs-stats"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"  # image-tag